package factory;

public enum TypeNeuron {
    CLASSIC_SIGMOID_INIT,
    ROOT_SIGMOID_INIT,
    NORMAL_SIGMOID_INIT,
    HALF_SIGMOID_INIT,

    CLASSIC_STEPPED_INIT,
    NORMAL_STEPPED_INIT,
    NORMAL_GIPERBOLIC_INIT,
    NORMAL_TEST_NOT_NULL_INIT
}
